### ISSUE TITLE
Скласти додаткові інформаційні блоки

### ISSUE THREAD

**Issue by danylokarpenko** [danylokarpenko/homepage#7]
Можна зробити резюме менш формальним, додавши додаткові блоки, які містять корисну інформацію, але подають її в "розважальній" формі. Наприклад, що подобається і не подобається, сильні і слабкі сторони, перелік навиків чи хобі, інфографіка або ж інтерактивні модулі, тощо. Варто написати контент такого блоку раніше, ніж починати верстку, бо його розміри впливатимуть на розміщення елементів на сторінці.

**Comment by testdanylokarpenko** [comment]
PERSONAL LIFE
2006
Melania gained United States citizenship and gave birth to our son, Barron

2005
Married her

1998
Met my future third wife, Melania Knauss

1999
Divorced Marla ¯_(ツ)_/¯

1993
Married Marla and had a daughter, we named her Tiffany, because I like Tiffany & Company jewellery as well

1992
Started affair with Marla Maples, so I had to divorce. God knows I love nice women, I love them all!

1984
Birth of Eric Trump

1982
Birth of Ivanka Trump

1977
My first son is born. I called him Donald, of course!

1977
Married Czech model Ivana Zelníčková

MEDIA CAREER
2019
Was awarded Worst Actor and Worst Screen Combo at Golden Raspberry Awards for parts in "Death of a Nation" and "Fahrenheit 11/9"

2015
Published a book "Crippled America: How to Make America Great Again"

2011
Published a book "Time to Get Tough: Making America #1 Again" in coauthorship with Wynton Hall, Peter Schweizer and Meredith McIver

2011
Published a book "Midas Touch: Why Some Entrepreneurs Get Rich – And Why Most Don't" in coauthorship with Robert Kiyosaki

2011
Published a book "Trump Tower" in coauthorship with Jeffrey Robinson

2009
Published a book "Think Like a Champion: An Informal Education in Business and Life" in coauthorship with Meredith McIver

2008
Published a book "Never Give Up: How I Turned My Biggest Challenges into Success" in coauthorship with Meredith McIver

2007
Published a book "Think Big and Kick Ass" in coauthorship with Bill Zanker

2007
Received a star on the Hollywood Walk of Fame for being producer of Miss Universe pageant

2006
Published a book "Why We Want You to Be Rich" in coauthorship with Meredith McIver and Robert Kiyosaki

2006
Published a book "How to Build a Fortune: Your Plan for Success From the World's Most Famous Businessman"

2006
Published a book "The Best Real Estate Advice I Ever Received: 100 Top Experts Share Their Strategies"

2006
Published a book "Trump 101: The Way to Success" in coauthorship with Meredith McIver

2005
Published a book "The Best Golf Advice I Ever Received"

2005
Performed a song with Megan Mullally at the 57th Primetime Emmy Awards

2004 ― 2008
Ran short-form talk radio program "Trumped!" (one to two minutes on weekdays)

2004
Published a book "Trump: How to Get Rich" in coauthorship with Meredith McIver

2004
Published a book "The Way to the Top: The Best Business Advice I Ever Received"

2004
Published a book "Think Like a Billionaire: Everything You Need to Know About Success, Real Estate, and Life" in coauthorship with Meredith McIver

2003 ― 2015
Produced NBC reality shows "The Apprentice" and "The Celebrity Apprentice"

2000
Published a book "Trump: The America We Deserve" in coauthorship with Dave Shiflett

1997
Published a book "Trump: The Art of the Comeback" in coauthorship with Kate Bohner

1991
Was awarded Worst Supporting Actor at Golden Raspberry Awards for a part in "Ghosts Can't Do It"

1990
Published a book "Trump: Surviving at the Top" in coauthorship with Charles Leerhsen

1987
Published a book "Trump: The Art of the Deal" in coauthorship with Tony Shwartz

EDUCATION
2011
Asked friends who are prominent and wealthy alumni of the New York Military Academy to secure my academic records so they could not be seen by anyone, never!

1966
Transferred to the Wharton School of the University of Pennsylvania and graduated in May 1968 with a B.S. in economics

1964
Started studying in Fordham University

1959
Enrolled in the New York Military Academy, a private boarding school, after my parents discovered I made frequent trips into Manhattan without their permission

LANGUAGES
us ENGLISH ru РУССКИЙ

SKILLS
NEGOTIATING COUNTING REMODELING WRITING ACING SINGING REPORTING INCORPORATING SELLING ADVERTISING HOSTING COMPETING TWITTING PARENTING GAMBLING DATING SUING ORGANIZING FUNDING DEBATING ADVISING PRESBYTERIANING

CHARACTER
ADJUSTED CALM AMBITIOUS COMPETITIVE SOCIABLE DIRECT HOSTILE CARELESS IGNORANT INQUISITIVE BOLD CONFIDENT MISCHIEVOUS CHARMING INTERESTING DARING COLORFUL LAZY SELF-PROMOTING

LIKES smiley
BILLIONS FILET-O-FISH BIG MAC CHINA QUARTER POUNDER DIET COKE TARIFFS BIBLE ARTOF DEAL PATRIOTS BEAUTIFUL MODELS GOLD REAL ESTATE WAR PROTESTERS CONSTRUCTION RUSSIANS BANKS SPORTS WOMEN MEXICO RED HAT KOREANS GOLF EVERYBODY [1] [2]

DISLIKES disappointed
DOGS MEDIA CNN GERMANS MEXICANS IMMIGRANTS SHITHOLE COUNTRIES UNATTRACTIVE WOMEN BLACKS SUSHI HOT-DOGS ALCOHOL FRUIT CHRISTMAS PARTIES LIBERALS

WANTS pleading_face
BE HEALTHY GROW A TREE BUILD TRUMP AIRPORT HAVE A TASTE DO A HARLEM SHAKE IN CONGRESS TO GOLF MORE OFTEN WIN ALL THE COURT SUITS
